---
title: Yasuhiro Sato
output: rmdformats::material
---

# ホーム

[[英語]](index.html) [[日本語]](index_jp.html)  

## **佐藤 安弘（サトウ ヤスヒロ）**  

### 現在の連絡先
Department of Evolutionary Biology and Environmental Studies, University of Zurich  
Winterthurerstrasse 190, 8057 Zurich, Switzerland  
Tel: +41-44-635-4986; Office: Y13-J-68 ([Kentaro K. Shimizu Group](https://www.ieu.uzh.ch/en/research/evolbiol/ecogenomics.html))  
E-mail: yasuhiro.sato(あっと)uzh.ch; yassato36c(あっと)outlook.com; sato.yasuhiro.36c(あっと)kyoto-u.jp  
研究者情報: ORCID:[0000-0002-6466-723X](http://orcid.org/0000-0002-6466-723X); [researchmap](https://researchmap.jp/yassatojpn/?lang=japanese); [Google scholar citations](http://scholar.google.co.jp/citations?user=HbrGYr8AAAAJ&hl=jp)  

---

**＊日本語の履歴書と業績一覧は[researchmap](https://researchmap.jp/yassatojpn/?lang=japanese)でも更新しています。**
  
---
  
  
<p align="center"><sup>(c) 2013- Yasuhiro Sato, All rights reserved.</sup></p>  


# 研究
- 植物の虫害に関する量的生態遺伝学（Sato et al. 2021 Heredity; Sato et al. G3他）
- 植物の虫害応答に関する生態機能ゲノミクス（Sato et al. 2019 Frontiers in Genetics; Sato et al. 2019 BMC Plant Biology）
- 植物防御の進化生態学（Sato & Kudoh 2017 American Naturalist; Sato et al. 2017 Functional Ecology; Sato 2018 Plant Species Biology他）
- 生態学・進化生物学・遺伝学におけるデータ解析（Takimoto & Sato et al. 2021 Ecological Informatics他）

専門分野：基礎生物学、生態・環境、動植物間相互作用  


# 業績

### 論文業績

#### 査読なし  
1. **Sato Y**, Takahashi Y, Xu C, Shimizu KK. (2022) Detecting frequency-dependent selection through the effects of genotype similarity on fitness components. **_bioRxiv_** <https://doi.org/10.1101/2022.08.10.502782>  

1. Stockenhuber R, Akiyama R, Tissot N, Yamazaki M, Wyler M, Arongaus AB, Podolec R, **Sato Y**, Milosavljevic S, Widmer A, Ulm R, Shimizu KK. (2021) The _UV RESISTANCE LOCUS 8_-mediated UV-B response is required alongside _CRYPTOCHROME1_ for plant survival under sunlight in the field. **_bioRxiv_** <https://doi.org/10.1101/2021.12.08.471623>

#### 査読あり 
1. Takimoto H^\*^, **Sato Y**^\*^, Nagano AJ, Shimizu KK, Kanagawa A. (2021) Using a two-stage convolutional neural network to rapidly identify tiny herbivorous beetles in the field. **_Ecological Informatics_** 66:101466 ^\*^Equal contribution <https://doi.org/10.1016/j.ecoinf.2021.101466>

1. **Sato Y**, Yamamoto E, Shimizu KK, Nagano AJ. (2021) Neighbor GWAS: incorporating neighbor genotypic identity into genome-wide association studies of field herbivory. **_Heredity_** 126(4):597–614. <https://doi.org/10.1038/s41437-020-00401-w> [[R package]](https://CRAN.R-project.org/package=rNeighborGWAS)  

1. **Sato Y**^\*^, Takeda K^\*^, Nagano AJ. (2021) Neighbor QTL: an interval mapping method for quantitative trait loci underlying plant neighborhood effects. **_G3; Genes|Genomes|Genetics_** 11(2):jkab017 ^\*^Equal contribution <https://doi.org/10.1093/g3journal/jkab017> [[R package]](https://CRAN.R-project.org/package=rNeighborQTL)  

1. Shimizu-Inatsugi R, Milosavljevic S, Shimizu KK, Schaepman-Strub G, Tanoi K, **Sato Y.** (2021) Metal accumulation and its effect on leaf herbivory in an allopolyploid species _Arabidopsis kamchatica_ inherited from a diploid hyperaccumulator _A. halleri_. **_Plant Species Biology_** 36(2):208–217. <https://doi.org/10.1111/1442-1984.12304>

1. **Sato Y**, Tezuka A, Kashima M, Deguchi A, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. (2019) Transcriptional variation in glucosinolate biosynthetic genes and inducible responses to aphid herbivory on field-grown _Arabidopsis thaliana_. **_Frontiers in Genetics_** 10:787 <https://doi.org/10.3389/fgene.2019.00787>

1. **Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. (2019) Plant trichomes and a single gene _GLABRA1_ contribute to insect community composition on field-grown _Arabidopsis thaliana_. **_BMC Plant Biology_** 19:163 <https://doi.org/10.1186/s12870-019-1705-2>

1. **Sato Y.** (2018) Associational effects and the maintenance of polymorphism in plant defense against herbivores: review and evidence. **_Plant Species Biology_** 33(2):91-108. <https://doi.org/10.1111/1442-1984.12201> [[postprint]](https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/234646?locale=en)

1. Nakadai R^\*^, Hashimoto K^\*^, Iwasaki T, **Sato Y.** (2018) Geographical co-occurrence of butterfly species: the importance of niche filtering by host plant species. **_Oecologia_** 186(4):995–1005. ^\*^Equal contribution <https://doi.org/10.1007/s00442-018-4062-1>

1. 坂田ゆず・**佐藤安弘**. (2017) 植物防御の進化生態学：種内と種間の異なる空間的階層を統合して. **日本生態学会誌** 67(3):287-306. <https://doi.org/10.18960/seitai.67.3_287>

1. **Sato Y**^\*^, Ito K^\*^, Kudoh H. (2017) Optimal foraging by herbivores maintains polymorphism in defence in a natural plant population. **_Functional Ecology_** 31(12):2233-2243. ^\*^Equal contribution <https://doi.org/10.1111/1365-2435.12937> [[postprint]](https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/228143?locale=en)

1. **Sato Y**, Kudoh H. (2017) Herbivore-mediated interaction promotes the maintenance of trichome dimorphism through negative frequency-dependent selection. **_The American Naturalist_** 190(3):E67-E77. <https://doi.org/10.1086/692603> [[PDF]](https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/226924?locale=en)

1. **Sato Y**, Kudoh H. (2017) Fine-scale frequency differentiation along a herbivory gradient in the trichome dimorphism of a wild _Arabidopsis_. **_Ecology and Evolution_** 7(7):2133-2141. <https://doi.org/10.1002/ece3.2830>

1. **Sato Y**, Kudoh H. (2016) Presence of substitute diets alters plant resistance to specialist and generalist herbivores: a meta-analysis. **_Ecosphere_** 7(11):e01446 <https://doi.org/10.1002/ecs2.1446>

1. **Sato Y**, Kudoh H. (2016) Associational effects against a leaf beetle mediate a minority advantage in defense and growth between hairy and glabrous plants. **_Evolutionary Ecology_** 30(1):137-154. <https://doi.org/10.1007/s10682-015-9809-0> [[postprint]](http://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/201635?locale=en)

1. **Sato Y**, Sato S. (2015) Spring temperature predicts the long-term molting phenology of two cicadas, _Cryptotympana facialis_ and _Graptopsaltria nigrofuscata_ (Hemiptera: Cicadidae). **_Annals of the Entomological Society of America_** 108(4):494-500. <https://doi.org/10.1093/aesa/sav036> [[postprint]](http://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/201636?locale=en)

1. **Sato Y**, Kudoh H. (2015) Tests of associational defence provided by hairy plants for glabrous plants of _Arabidopsis halleri_ subsp. _gemmifera_ against insect herbivores. **_Ecological Entomology_** 40(3):269-279. <https://doi.org/10.1111/een.12179> [[postprint]](http://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/201637?locale=en)

1. **Sato Y**, Kudoh H. (2014) Fine-scale genetic differentiation of a temperate herb: relevance of local environments and demographic change. **_AoB PLANTS_** 6:plu070. <https://doi.org/10.1093/aobpla/plu070>

1. **Sato Y**, Kawagoe T, Sawada Y, Hirai MY, Kudoh H. (2014) Frequency-dependent herbivory by a leaf beetle, _Phaedon brassicae_, on hairy and glabrous plants of _Arabidopsis halleri_ subsp. _gemmifera_. **_Evolutionary Ecology_** 28(3):545-559. <https://doi.org/10.1007/s10682-013-9686-3> [[postprint]](http://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/179616?locale=en)

1. **Sato Y**, Kudoh H. (2013) Relative strength of phenotypic selection on the height and number of flowering-stalks in the rosette annual _Cardamine hirsuta_ (Brassicaceae). **_Journal of Ecology and Environment_** 36(3):151-158. <https://doi.org/10.5141/ecoenv.2013.151>

1. **Sato Y**, Takakura KI, Nishida S, Nishida T. (2013) Dominant occurrence of cleistogamous flowers of _Lamium amplexicaule_ in relation to the nearby presence of an alien congener _L. purpureum_. **_ISRN Ecology_** Article ID:476862. <http://dx.doi.org/10.1155/2013/476862>  

## 学会・シンポジウム発表

### 国際学会・シンポジウム発表

1. **Sato Y**, Takahashi Y, Xu C, Shimizu KK. Detecting frequency-dependent selection using a genetic marker regression of fitness components. In: S24 'Progress and Prospects in Adaptation Genomics'. **_The 2022 Congress of the European Society for Evolutionary Biology_**, Prague, Czech Republic (a talk accepted and scheduled on 18 August 2022)

1. **Sato Y**, Nagano AJ, Shimizu KK. Genomics of within-species mixed planting against insect herbivores. In: Symposium MON3-b “From the species to the individual: investigating plant diversity on the scale that matters most”. **_World Biodiversity Forum 2022_**, June 26-July 1 2022, Davos, Switzerland [reviewed talk]

1. Kuzuhara H, Takimoto H, **Sato Y**, Kanagawa A. Insect pest detection and identification method based on deep learning for realizing a pest control system. **_The SICE 2020 Annual Conference_**, September 23-26, 2020. Chiang Mai, Thailand [reviewed talk, changed into online meeting]

1. **Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Nagano AJ, Shimizu KK. Field GWAS of neighbor effects and its potential application to targeted polycultures in anti-herbivore defense. **_URPP Global Change and Biodiversity Conference_**, P15, June-July 2019, Monte Verita, Ascona, Switzerland [non-reviewed poster]

1. **Sato Y**. Using personal legacy data to reveal the molting phenology of Japanese cicadas.**_The 8th EAFES International Congress_**, In: S19 "Ongoing cicada research in East Asia" (organized by Prof. J. Yikweon), April 2018, Nagoya, Japan [invited talk]

1. **Sato Y**, Ito K, Kudoh H. Associational effects and the maintenance of trichome dimorphism in a wild *Arabidopsis*.**_The 2017 Congress of the European Society for Evolutionary Biology_**, S32-P08, 24 August 2017, Groningen, Netherland [reviewed poster]

1. **Sato Y**, Ito K. Modeling the effects of optimal foraging herbivores on the maintenance of trichome dimorphism in a wild *Arabidopsis population*.**_URPP Global Change and Biodiversity Conference_**, P28, August-September 2016, Monte Verita, Ascona, Switzerland [non-reviewed poster]

1. **Sato Y**, Kudoh H. Associational antiherbivore defense promotes the coexistence of hairy and glabrous plants. **_100th Annual Meeting of Ecological Society of America_**, PS30-98, August 2015, Baltimore, MD, USA [reviewed poster]

1. **Sato Y**, Kudoh H. Associational anti-herbivore defence and the maintenance of hairy and glabrous plants in *Arabidopsis halleri* subsp. *gemmifera*. **_Bristol-Kyoto Plant Sciences Workshop_**, P-14, September 2014, Bristol, UK [non-reviewed poster]

1. **Sato Y**, Kudoh H. Factors responsible for plant resistance to a shared herbivore: a meta-analysis of herbivore responses between choice and no-choice conditions.**_International Symposium for "Biodiversity & Evolution" project of Excellent Graduate Schools_**, P-03, December 2013, Kyoto, Japan [non-reviewed poster]

1. **Sato Y**, Kawagoe T, Kudoh H. A test for frequency-dependent herbivory on two trichome morphs of *Arabidopsis halleri* . **_The 5th EAFES International Congress_**, P2-147A, March 2012, Otsu, Japan [non-reviewed poster]

### 国内学会・シンポジウム発表

1. **佐藤安弘.** 正の連合効果をもたらす植物のゲノム基盤とその拡張可能性. S07:植物-植物相互作用の多様性と普遍性：植物群集の統合的理解に向けて. **_第69回日本生態学会大会_**, 福岡（オンライン）, S07-4, 2022年3月（招待講演, 企画者：内海俊介准教授・山尾僚准教授）

1. **佐藤安弘**, 武田和也, 永野惇. 近傍個体を考慮したQTL解析の開発と虫害への応用. **_第68回日本生態学会大会_**, P2-036, 岡山（オンライン）, 2021年3月（ポスター・査読なし）

1. **Sato Y**, Yamamoto E, Shimizu KK, Nagano AJ. Neighbor GWAS: incorporating neighbor genotypic identity into genome-wide association studies of field herbivory on *Arabidopsis thaliana*. **_第61回日本植物生理学会年会_**, PF-192, 大阪, 2020年3月（ポスター・査読なし）

1. **Sato Y**, Yamamoto E, Shimizu KK, Nagano AJ. Neighbor GWAS: incorporating neighbor genotypic identity into genome-wide association studies of simulated traits and field herbivory.**_第67回日本生態学会大会_**, P2-PA-066, 名古屋, 2020年3月（ポスター・査読なし）

1. **佐藤安弘**, 山本英司, 清水健太郎, 永野惇. 近傍個体を考慮したGWASの開発と虫害への適用. **_第5回農学中手の会研究集会_**, 滋賀, 2019年12月（主催者：内藤健博士）

1. **佐藤安弘**, 村中智明. 使ってみよう先端技術！-オミクス解析と形質測定で迫る植物の生き様. **_第51回種生物学シンポジウム_**, 宮崎, 2019年12月（シンポジウム企画者）

1. 葛原宏章, 滝本裕則, **佐藤安弘**, 金川明弘. 動画像からの病害虫の検出・識別に関する検討. **_第21回IEEE広島支部学生シンポジウム_**, 岡山, 2019年11月（ポスター・査読あり）

1. **佐藤安弘**, 清水(稲継)理恵, 山﨑美紗子, 清水健太郎, 永野惇. Genomic basis of neighbor effects in *Arabidopsis* defense against insect herbivores.S03企画シンポジウム：オミクスから見た表現型多型・頑健性と倍数体種分化-進化学・生態学・育種学の統合を目指して. **_日本進化学会第21回大会_**, 北海道, 2019年8月 （招待講演, 企画者：清水健太郎教授）

1. **佐藤安弘**, 清水(稲継)理恵, 山﨑美紗子, 清水健太郎, 永野惇. 植物個体間の相互作用を考慮した虫害の全ゲノム関連解析. **_第66回日本生態学会大会_**, B2-02, 神戸, 2019年3月（口頭・査読なし）

1. **Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. Incorporating neighbor identity into a genome-wide association mapping of insect herbivory. **_第60回日本植物生理学会年会_**, 1aO10, 名古屋, 2019年3月（口頭・査読なし）

1. **佐藤安弘**, 清水(稲継)理恵, 山﨑美紗子, 清水健太郎, 永野惇.  植物防御の連合効果を考慮したゲノムワイド関連解析. **_第50回種生物学シンポジウム_**, A-4, 八王子, 2018年12月（ポスター・査読なし）

1. **佐藤安弘**, 清水(稲継)理恵, 山﨑美紗子, 清水健太郎, 永野惇. ゲノムワイド関連解析を応用した混植効果の推定と虫害予測, **_予測モデリングとその周辺 -機械学習・統計科学・情報理論からのアプローチ-_**, 成蹊大学, 2018年11月（招待講演, 企画者：小森理准教授・深谷肇一博士）

1. 葛原宏章、滝本裕則、**佐藤安弘**、金川明弘. 深層学習に基づく動画像からの病害虫の検出. **_第20回IEEE広島支部学生シンポジウム_**, 鳥取, 2018年11月（ポスター・査読あり）

1. **佐藤安弘**. 植物のゲノム多型を用いた遺伝子型間相互作用の推定と虫害予測. S1-03企画シンポジウム：種多様性と遺伝的多様性の対比からみる多様性-機能関係. **_第34回個体群生態学会_**, 東京, 2018年10月 (招待講演, 企画者：高橋佑磨助教・村上正志教授)

1. **佐藤安弘**, 滝本裕則. アブラナ科植物を食害する微小昆虫の野外調査と動画像計測の試み. MC：農学・植物科学研究における計測技術. **_平成30年電気学会 電子・情報・システム部門大会_**, 札幌, 2018年9月 (招待講演, 企画者：七夕高也博士・磯部祥子博士)

1. **Sato Y**, Tezuka A, Kashima M, Deguchi A, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. Field transcriptome reveals natural variation in constitutive and inducible responses to insect herbivory on *Arabidopsis thaliana*. **_第59回日本植物生理学会年会_**, P393, 札幌, 2018年3月（ポスター・査読なし）

1. 橋本洸哉, 中臺亮介, 岩崎貴也, **佐藤安弘**. 寄主植物の共有が日本列島に分布する蝶類の共起パターンに与える影響. **_第65回日本生態学会大会_**, P1-087, 札幌, 2018年3月 (ポスター・査読なし) (ポスター賞受賞)

1. **佐藤安弘**, 伊藤公一, 工藤洋. 植食者の最適採餌からみたハクサンハタザオのトライコーム多型の維持. **_第65回日本生態学会大会_**, D02-06, 札幌, 2018年3月（口頭・査読なし）

1. **佐藤安弘**, 手塚あゆみ, 鹿島誠, 出口亜由美, 清水(稲継)理恵, 山﨑美紗子, 清水健太郎, 永野惇. 野外栽培したシロイヌナズナの遺伝子発現からみた食害応答の恒常性と可塑性. **_第49回種生物学シンポジウム_**, B-37, 福井, 2017年12月（ポスター・査読なし）

1. **Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. Quantifying the variability of insect communities among *Arabidopsis thaliana* genotypes: tests for the effects of trichomes and glucosinolates. **_第64回日本生態学会大会_**, P2-I-275, 東京, 2017年3月（ポスター・査読なし）

1. **佐藤安弘**. 微細な変異から紐解くシロイヌナズナ属植物の対被食防御、**_第48回種生物学シンポジウム_**, 北海道, 2016年12月（口頭・受賞講演）

1. **佐藤安弘**, 伊藤公一, 工藤洋. 植食者の最適採餌からみたハクサンハタザオのトライコーム二型の維持. **_第48回種生物学シンポジウム_**, B-6, 北海道, 2016年12月（ポスター・査読なし）

1. **佐藤安弘**, 工藤洋. 植食者を介した頻度依存選択がハクサンハタザオの細毛多型の維持を促す, **_第63回日本生態学会大会_**, D2-10, 仙台, 2016年3月（口頭・査読なし）

1. **佐藤安弘**、工藤洋. 複数植食者からなる食害傾度に応じたトライコーム二型の地理的変異. **_第47回種生物学シンポジウム_**, P44, 岐阜, 2015年12月（ポスター・査読なし）

1. **Sato Y**, Kudoh H. Herbivore-mediated interaction promotes the local coexistence of trichome dimorphism in a plant population. **_第31回個体群生態学会大会_**, P43, 彦根, 2015年10月 (ポスター・査読なし)

1. **佐藤安弘**. 被食防御の連合効果がハクサンハタザオにおける細毛二型の存続性に与える影響, **_進化群集生態学シンポジウム2015_**. 京都, 2015年9月 (招待講演, 企画者：門脇浩明博士・金尾太輔博士)

1. **佐藤安弘**、工藤洋. 被食防御の連合効果がハクサンハタザオのトリコーム多型を維持する, **_第62回日本生態学会大会_**, PA1-113, 鹿児島, 2015年3月 (ポスター・査読なし)

1. 坂田ゆず、**佐藤安弘**. 植物と植食性昆虫の相互作用が生み出す進化・生態現象を俯瞰する. **_第62回日本生態学会大会_**, W12, 鹿児島, 2015年3月 (集会企画) -> [W12-3] **佐藤安弘**. 被食防御の連合効果がもたらす多型の維持：ハクサンハタザオの細毛を例に

1. **佐藤安弘**, 工藤洋. 被食防御の連合効果がもたらすハクサンハタザオのトリコーム多型の維持. **_日本生態学会近畿地区第2回例会_**, 発表(2), 大阪, 2014年12月 (口頭・査読なし)

1. **Sato Y**, Kudoh H. The presence of substitute diets alters plant resistance to a shared herbivore: a meta-analysis of herbivore responses under choice and no-choice conditions. **_第61回日本生態学会大会_**, G0-05, 広島, 2014年3月（英語口頭・査読なし）

1. **佐藤安弘**, 工藤洋. となりの餌の存在が植物の植食者に対する抵抗性を変える：メタ解析による餌選択実験の結果の統合. **_第45回種生物学シンポジウム_**, P-20, 別府, 2013年12月（ポスター・査読なし）

1. **佐藤安弘**, 川越哲博, 工藤洋. ハクサンハタザオの有毛型と無毛型に対する食害の頻度依存性.**_第60回日本生態学会大会_**, P1-121, 静岡, 2013年3月（ポスター・査読なし）

1. **佐藤安弘**, 川越哲博, 工藤洋. ハクサンハタザオの有毛型と無毛型に対するハムシの頻度依存餌選択. **_第44回種生物学会シンポジウム_**, P3, 滋賀マキノ, 2012年12月（ポスター・査読なし）

1. **佐藤安弘**, 川越哲博, 工藤洋. 有毛型・無毛型の頻度がハクサンハタザオの被食防衛効果を変える. **_第28回個体群生態学会大会_**, P02, 千葉, 2012年10月（ポスター・査読なし）

1. **佐藤安弘**, 高倉耕一, 西田隆義. 近縁外来種の存在がホトケノザの閉鎖花率に与える影響. **_第26回個体群生態学会大会_**, P2-10, 横浜, 2010年9月（ポスター・査読なし）

1. **佐藤安弘**, 高倉耕一, 西田佐知子, 西田隆義. 近縁外来種との共存がホトケノザの閉鎖花に与える影響. **_第42回種生物学シンポジウム_**, P-16, 京都, 2010年12月（ポスター・査読なし）

### 外部セミナーなど

1. **Sato Y**. Neighbor GWAS: incorporating neighbor identity into *Arabidopsis*-herbivore interaction. Gregor Mendel Institute of Molecular Plant Biology, Austria (June 2019) (Host: Dr. Magnus Nordborg) 

1. **佐藤安弘**. Ecological genomics of neighbor effects in *Arabidopsis* defense against insect herbivores (シロイヌナズナ野生系統を用いた虫害防御の生態ゲノミクス：近傍個体に着目して). 奈良先端科学技術大学院大学, 2019年2月 (世話人：晝間敬助教)

1. **佐藤安弘**. 周りの植物が防御効果を変える：アブラナ科植物における多型の維持から虫害制御へ. 昆虫生態学格致セミナー, 京都大学農学部, 2018年9月（世話人：松浦健二教授）

1. **Sato Y**. Neighbor effects enhance anti-herbivore defense in *Arabidopsis*. URPP GCB seminar, University of Zurich, Switzerland (August 2018)

1. **佐藤安弘**. 混植によって改変されるシロイヌナズナ属植物と植食者の関係：多型の維持から虫害制御へ. 森林生物特別セミナー, 京都大学農学部, 2018年1月（世話人：井鷺裕司教授）

1. **佐藤安弘**. アブラナ科植物における防御多型の維持から虫害制御へ向けて. 龍谷エコロジーセミナー, 龍谷大学理工学部, 2017年11月（世話人：近藤倫生教授）

### その他

1. 第52回種生物学シンポジウム. 食べられないために守る術ー植物の多様な対被食者防御戦略ー. コメンテータ. 滋賀（オンライン）2020年12月（企画者：坂田ゆず助教・角田智詞博士）

1. 進化群集生態学シンポジウム2018. ディスカッション・パネリスト. 京都、2018年9月 (企画者：門脇浩明博士・三木健教授)


# 略歴

### 学歴
- 2016年　京都大学理学研究科　生物科学専攻植物学系　生態科学II　博士後期課程修了　博士(理学)  
- 2013年　京都大学理学研究科　生物科学専攻植物学系　生態科学II　修士課程修了  
- 2011年　京都大学農学部　資源生物科学科卒  
- 2007年　三重県立桑名高等学校　普通科卒  

### 学位論文
- 2016年　Associational anti-herbivore defense in the trichome dimorphism of *Arabidopsis halleri* subsp. *gemmifera* (Brassicaceae) (ハクサンハタザオ（アブラナ科）のトライコームによる被食防御における連合効果). 京都大学, 理博第4196号,  指導：[工藤洋](http://www.ecology.kyoto-u.ac.jp/~kudoh/)教授.

### 研究歴・職歴
- 2021年4月-現在まで　チューリッヒ大学　進化生物学・環境学研究所　上級助手（[清水研究室]((https://www.ieu.uzh.ch/en/research/evolbiol/ecogenomics.html))）  
- 2017年10月-現在まで　龍谷大学　食と農の総合研究所　客員研究員（受入：[永野惇](http://ps.agr.ryukoku.ac.jp/naganolab/)准教授）  
- 2017年7月-現在まで　チューリッヒ大学[URPP GCBプログラム](https://www.gcb.uzh.ch/en/aboutus/people.html)　連携メンバー  
- 2017年10月-2021年3月　[科学技術振興機構　さきがけ専任研究者](https://www.jst.go.jp/kisoken/presto/project/1112074/1112074_26.html) (受入機関：龍谷大学)  
- 2016年4月-2020年3月　京都大学生態学研究センター　協力研究員  
- 2016年4月-2017年9月　日本学術振興会　特別研究員PD (受入: [永野惇](http://ps.agr.ryukoku.ac.jp/naganolab/)講師\)  
- 2015年4月-2016年3月　日本学術振興会　特別研究員DC2  
- 2013年6月-2014年3月　京都大学生態学研究センターRA  

### 教育歴
- 2021年9月-現在まで　BIO373. Next Generation Sequencing for Evolutionary Functional Genomics, University of Zurich, Switzerland (Block course coordinator, Co-instructor)  
- 2022.05: BIO334. Practical Bioinformatics (Co-instructor)  
- 2019年4月-2019年5月　龍谷大学農学部　非常勤講師『遺伝の考え方』(分担5回)  
- 2018年7月-2018年8月　International Biology Undergraduate Summer School (BUSS) 2018, University of Zurich, Switzerland (Co-supervisor)  
- 2017年7月-2017年8月　BIO378. Research Practical in Evolutionary Biology and Systematics, University of Zurich, Switzerland (Co-supervisor)  
- 2013年9月-2015年1月　龍谷大学理工学部　学外ティーチングアシスタント『計算機基礎実習』(半期×2年)  

### 獲得研究費
1. 2020-2023年　日本学術振興会　科学研究費助成事業　若手研究（研究代表者として総額3200千円見込み）
1. 2017-2021年　科学技術振興機構　さきがけ「フィールド植物制御」領域（研究代表者として総額40000千円）  
1. 2016-2017年　日本学術振興会　特別研究員奨励費PD（研究代表者として総額2700千円）  
1. 2015-2016年　日本学術振興会　特別研究員奨励費DC2（研究代表者として総額1200千円）  

### 賞罰
- 2018年　井上科学振興財団　第34回　井上研究奨励賞  
- 2016年　種生物学会　第10回　片岡奨励賞  
- 2016年　日本学術振興会　第6回　育志賞  
- 2013-2015年　日本学生支援機構第一種奨学金　特に優れた業績による返還免除 （博士課程貸与分・全額免除）  
- 2011-2013年　日本学生支援機構第一種奨学金　特に優れた業績による返還免除 （修士課程貸与分・半額免除）  

### 委員歴・学術貢献活動
- 2019年1月-現在まで　種生物学会　[和文誌編集委員](http://www.speciesbiology.org/board/index.html)  
- 2019年9月-2021年12月　Reviewing Editor of *Journal of Evolutionary Biology*    
- 2020年12月　[第52回種生物学シンポジウム実行委員](https://sites.google.com/view/sssb2020shiga)  
- 2016年11月　[5th Japan-Taiwan Ecology Workshop](https://sites.google.com/site/jtecolw5th/)実行委員  

### 学術誌等における査読 
- [Publons](https://publons.com/researcher/450213/yasuhiro-sato)を参照.  

