---
output:
  html_document: default
  pdf_document: default
---
# 佐藤安弘の学会発表リスト(Yasuhiro Sato's presentation list)

## 国際学会・シンポジウム発表 (International presentation)

1.	Kuzuhara H, Takimoto H, **Sato Y**, Kanagawa A.「Insect pest detection and identification method based on deep learning for realizing a pest control system」. The SICE 2020 Annual Conference, September 23-26, 2020. Chiang Mai, Thailand [reviewed talk, changed into online meeting]

1.	**Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Nagano AJ, Shimizu KK.「Field GWAS of neighbor effects and its potential application to targeted polycultures in anti-herbivore defense」.『URPP Global Change and Biodiversity Conference』, P15, Monte Verita, Ascona, Switzerland (June-July 2019) [non-reviewed poster]

1.	**Sato Y**.「Using personal legacy data to reveal the molting phenology of Japanese cicadas」.『The 8th EAFES International Congress』, S19: Ongoing cicada research in East Asia (organized by Prof. J. Yikweon), Nagoya, Japan (April 2018) [invited talk]

1.	**Sato Y**, Ito K, Kudoh H.「Associational effects and the maintenance of trichome dimorphism in a wild *Arabidopsis*」.『The 2017 Congress of the European Society for Evolutionary Biology』, S32-P08, Groningen, Netherland (24 August 2017) [reviewed poster]

1.	**Sato Y**, Ito K.「Modeling the effects of optimal foraging herbivores on the maintenance of trichome dimorphism in a wild *Arabidopsis population*」.『URPP Global Change and Biodiversity Conference』, P28, Monte Verita, Ascona, Switzerland (August-September 2016) [non-reviewed poster]

1.	**Sato Y**, Kudoh H.「Associational antiherbivore defense promotes the coexistence of hairy and glabrous plants」.『100th Annual Meeting of Ecological Society of America』, PS30-98, Baltimore, MD, USA (August 2015) [reviewed poster]

1.	**Sato Y**, Kudoh H.「Associational anti-herbivore defence and the maintenance of hairy and glabrous plants in *Arabidopsis halleri* subsp. *gemmifera*」.『Bristol-Kyoto Plant Sciences Workshop』, P-14, Bristol, UK (September 2014) [non-reviewed poster]

1.	**Sato Y**, Kudoh H.「Factors responsible for plant resistance to a shared herbivore: a meta-analysis of herbivore responses between choice and no-choice conditions」.『International Symposium for "Biodiversity & Evolution" project of Excellent Graduate Schools』, P-03, Kyoto, Japan (December 2013) [non-reviewed poster]

1.	**Sato Y**, Kawagoe T, Kudoh H.「A test for frequency-dependent herbivory on two trichome morphs of *Arabidopsis halleri*」.『The 5th EAFES International Congress』, P2-147A, Otsu, Japan (March 2012) [non-reviewed poster]

## 国内学会・シンポジウム発表 (Presentation in Japanese)

1.	**佐藤安弘**、武田和也、永野惇. 「近傍個体を考慮したQTL解析の開発と虫害への応用」. 『第68回日本生態学会大会』、P2-036、岡山（オンライン）、2021年3月（ポスター・査読なし）

1.	**Sato Y**, Yamamoto E, Shimizu KK, Nagano AJ.「Neighbor GWAS: incorporating neighbor genotypic identity into genome-wide association studies of field herbivory on *Arabidopsis thaliana*」、『第61回日本植物生理学会年会』、PF-192、大阪、2020年3月（ポスター・査読なし）

1.	**Sato Y**, Yamamoto E, Shimizu KK, Nagano AJ.「Neighbor GWAS: incorporating neighbor genotypic identity into genome-wide association studies of simulated traits and field herbivory」、『第67回日本生態学会大会』、P2-PA-066、名古屋、2020年3月（ポスター・査読なし）

1.	**佐藤安弘**、山本英司、清水健太郎、永野惇. 「近傍個体を考慮したGWASの開発と虫害への適用」. 『第5回農学中手の会研究集会』、滋賀、2019年12月（主催者：内藤健）

1.	**佐藤安弘**、村中智明.「使ってみよう先端技術！-オミクス解析と形質測定で迫る植物の生き様」. 『第51回種生物学シンポジウム』、宮崎、2019年12月（シンポジウム企画者）

1.	葛原宏章、滝本裕則、**佐藤安弘**、金川明弘. 「動画像からの病害虫の検出・識別に関する検討」、『第21回IEEE広島支部学生シンポジウム』、岡山、2019年11月（ポスター・査読あり）

1.	**佐藤安弘**、清水(稲継)理恵、山﨑美紗子、清水健太郎、永野惇.「Genomic basis of neighbor effects in *Arabidopsis* defense against insect herbivores」、『日本進化学会第21回大会』、S03企画シンポジウム：オミクスから見た表現型多型・頑健性と倍数体種分化-進化学・生態学・育種学の統合を目指して、北海道、2019年8月 (招待講演, 企画者：清水健太郎)

1.	**佐藤安弘**、清水(稲継)理恵、山﨑美紗子、清水健太郎、永野惇. 「植物個体間の相互作用を考慮した虫害の全ゲノム関連解析」、『第66回日本生態学会大会』、B2-02、神戸、2019年3月（口頭・査読なし）

1.	**Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. 「Incorporating neighbor identity into a genome-wide association mapping of insect herbivory」、『第60回日本植物生理学会年会』、1aO10、名古屋、2019年3月（口頭・査読なし）

1.	**佐藤安弘**、清水(稲継)理恵、山﨑美紗子、清水健太郎、永野惇. 「植物防御の連合効果を考慮したゲノムワイド関連解析」、『第50回種生物学シンポジウム』、A-4、八王子、2018年12月（ポスター・査読なし）

1.	**佐藤安弘**、清水(稲継)理恵、山﨑美紗子、清水健太郎、永野惇. 「ゲノムワイド関連解析を応用した混植効果の推定と虫害予測」、『予測モデリングとその周辺 -機械学習・統計科学・情報理論からのアプローチ-』、成蹊大学、2018年11月（招待講演, 企画者：小森理・深谷肇一）

1.	葛原宏章、滝本裕則、**佐藤安弘**、金川明弘. 「深層学習に基づく動画像からの病害虫の検出」、『第20回IEEE広島支部学生シンポジウム』、鳥取、2018年11月（ポスター・査読あり）

1.	**佐藤安弘**.「植物のゲノム多型を用いた遺伝子型間相互作用の推定と虫害予測」、『第34回個体群生態学会』、S1-03企画シンポジウム：種多様性と遺伝的多様性の対比からみる多様性-機能関係、東京、2018年10月 (招待講演, 企画者：高橋佑磨・村上正志)

1.	**佐藤安弘**、滝本裕則.「アブラナ科植物を食害する微小昆虫の野外調査と動画像計測の試み」、『平成30年 電気学会 電子・情報・システム部門大会』、MC：農学・植物科学研究における計測技術、札幌、2018年9月 (招待講演, 企画者：七夕高也・磯部祥子)

1.	**Sato Y**, Tezuka A, Kashima M, Deguchi A, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. 「Field transcriptome reveals natural variation in constitutive and inducible responses to insect herbivory on *Arabidopsis thaliana*」、『第59回日本植物生理学会年会』、P393、札幌、2018年3月 （ポスター・査読なし）

1.	橋本洸哉、中臺亮介、岩崎貴也、**佐藤安弘**.「寄主植物の共有が日本列島に分布する蝶類の共起パターンに与える影響」、『第65回日本生態学会大会』、P1-087、札幌、2018年3月 (ポスター・査読なし) (ポスター賞受賞)

1.	**佐藤安弘**、伊藤公一、工藤洋. 「植食者の最適採餌からみたハクサンハタザオのトライコーム多型の維持」、『第65回日本生態学会大会』、D02-06、札幌、2018年3月 （口頭・査読なし）

1.	**佐藤安弘**、手塚あゆみ、鹿島誠、出口亜由美、清水(稲継)理恵、山﨑美紗子、清水健太郎、永野惇. 「野外栽培したシロイヌナズナの遺伝子発現からみた食害応答の恒常性と可塑性」、『第49回種生物学シンポジウム』、B-37、福井、2017年12月 （ポスター・査読なし）

1.	**Sato Y**, Shimizu-Inatsugi R, Yamazaki M, Shimizu KK, Nagano AJ. 「Quantifying the variability of insect communities among *Arabidopsis thaliana* genotypes: tests for the effects of trichomes and glucosinolates」、『第64回日本生態学会大会』、P2-I-275、東京、2017年3月 （ポスター・査読なし）

1.	**佐藤安弘**. 「微細な変異から紐解くシロイヌナズナ属植物の対被食防御」、『第48回種生物学シンポジウム』、北海道、2016年12月 （口頭・受賞講演）

1.	**佐藤安弘**、伊藤公一、工藤洋. 「植食者の最適採餌からみたハクサンハタザオのトライコーム二型の維持」、『第48回種生物学シンポジウム』、B-6、北海道、2016年12月 （ポスター・査読なし）

1.	**佐藤安弘**、工藤洋. 「植食者を介した頻度依存選択がハクサンハタザオの細毛多型の維持を促す」、『第63回日本生態学会大会』、D2-10、仙台、2016年3月 （口頭・査読なし）
1.	**佐藤安弘**、工藤洋. 「複数植食者からなる食害傾度に応じたトライコーム二型の地理的変異」、『第47回種生物学シンポジウム』、P44、岐阜、2015年12月 （ポスター・査読なし）

1.	**Sato Y**, Kudoh H. 「Herbivore-mediated interaction promotes the local coexistence of trichome dimorphism in a plant population」、『第31回個体群生態学会大会』、P43、彦根、2015年10月 (ポスター・査読なし)

1.	**佐藤安弘**. 「被食防御の連合効果がハクサンハタザオにおける細毛二型の存続性に与える影響」、『進化群集生態学シンポジウム2015』、京都、2015年9月 (招待講演, 企画者：門脇浩明・金尾太輔)

1.	**佐藤安弘**、工藤洋. 「被食防御の連合効果がハクサンハタザオのトリコーム多型を維持する」、『第62回日本生態学会大会』、PA1-113、鹿児島、2015年3月 (ポスター・査読なし)

1.	坂田ゆず、**佐藤安弘**. 「植物と植食性昆虫の相互作用が生み出す進化・生態現象を俯瞰する」、『第62回日本生態学会大会』、W12、鹿児島、2015年3月 (集会企画) -> [W12-3] **佐藤安弘**. 「被食防御の連合効果がもたらす多型の維持：ハクサンハタザオの細毛を例に」

1.	**佐藤安弘**、工藤洋. 「被食防御の連合効果がもたらすハクサンハタザオのトリコーム多型の維持」、『日本生態学会近畿地区第2回例会』、発表(2)、大阪、2014年12月 (口頭・査読なし)

1.	**Sato Y**, Kudoh H. 「The presence of substitute diets alters plant resistance to a shared herbivore: a meta-analysis of herbivore responses under choice and no-choice conditions」、『第61回日本生態学会大会』、G0-05、広島、2014 年3 月 （英語口頭・査読なし）

1.	**佐藤安弘**、工藤洋. 「となりの餌の存在が植物の植食者に対する抵抗性を変える：メタ解析による餌選択実験の結果の統合」、『第45回種生物学シンポジウム』、P-20、別府、2013年12月 （ポスター・査読なし）

1.	**佐藤安弘**、川越哲博、工藤洋. 「ハクサンハタザオの有毛型と無毛型に対する食害の頻度依存性」、『第60回日本生態学会大会』、P1-121、静岡、2013年3月 （ポスター・査読なし）

1.	**佐藤安弘**、川越哲博、工藤洋. 「ハクサンハタザオの有毛型と無毛型に対するハムシの頻度依存餌選択」、『第44回種生物学会シンポジウム』、P3、滋賀マキノ、2012年12月 （ポスター・査読なし）

1.	**佐藤安弘**、川越哲博、工藤洋. 「有毛型・無毛型の頻度がハクサンハタザオの被食防衛効果を変える」、『第28回個体群生態学会大会』、P02、千葉、2012年10月 （ポスター・査読なし）

1.	**佐藤安弘**、高倉耕一、西田隆義. 「近縁外来種の存在がホトケノザの閉鎖花率に与える影響」、『第26回個体群生態学会大会』、P2-10、横浜、2010年9月 （ポスター・査読なし）

1.	**佐藤安弘**、高倉耕一、西田佐知子、西田隆義. 「近縁外来種との共存がホトケノザの閉鎖花に与える影響」、『第42回種生物学シンポジウム』、P-16、京都、2010年12月 （ポスター・査読なし）

## 外部セミナーなど (External seminars)

1.	**Sato Y**.「Neighbor GWAS: incorporating neighbor identity into *Arabidopsis*-herbivore interaction」. Gregor Mendel Institute of Molecular Plant Biology, Austria (June 2019) (Host: Group Leader Dr. Magnus Nordborg)

1.	**佐藤安弘**.「Ecological genomics of neighbor effects in *Arabidopsis* defense against insect herbivores(シロイヌナズナ野生系統を用いた虫害防御の生態ゲノミクス：近傍個体に着目して)」、奈良先端科学技術大学院大学、2019年2月 (世話人：晝間敬助教)

1.	**佐藤安弘**.「周りの植物が防御効果を変える：アブラナ科植物における多型の維持から虫害制御へ」、『昆虫生態学格致セミナー』、京都大学農学部、2018年9月（世話人：松浦健二教授）

1.	**Sato Y**.「Neighbor effects enhance anti-herbivore defense in *Arabidopsis*」. URPP GCB seminar, University of Zurich, Switzerland (August 2018)

1.	**佐藤安弘**.「混植によって改変されるシロイヌナズナ属植物と植食者の関係：多型の維持から虫害制御へ」、『森林生物特別セミナー』、京都大学農学部、2018年1月（世話人：井鷺裕司教授）

1.	**佐藤安弘**.「アブラナ科植物における防御多型の維持から虫害制御へ向けて」、『龍谷エコロジーセミナー』、龍谷大学理工学部、2017年11月（世話人：近藤倫生教授）

## その他 (Others)

1.	第52回種生物学シンポジウム「食べられないために守る術ー植物の多様な対被食者防御戦略ー」. コメンテータ. 滋賀（オンライン）2020年12月（企画者：坂田ゆず助教・角田智詞博士）

1.	進化群集生態学シンポジウム2018. ディスカッション・パネリスト. 京都、2018年9月 (企画者：門脇浩明博士・三木健教授)

1.	Organizing committee member of “5th Japan-Taiwan Ecology Workshop”, Kyoto, Japan (November, 2016) [https://sites.google.com/site/jtecolw5th/]
